services:
  php:
  # https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-apache-dev.html
    image: webdevops/php-apache-dev:8.3
    ports:
      - "9000:80"
  # php:
  #   image: php:8.2-fpm
  #   ports:
  #     - "9000:9000"
    container_name: php
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_CLIENT_HOST=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # - ./src:/var/www/html
      # - ./src:/app
      - ./:/app
      - ./vhost:/opt/docker/etc/httpd/vhost.common.d
  